[package]
name = "triomphe"
version = "0.1.0"
authors = ["The Servo Project Developers"]
license = "MIT/Apache-2.0"
repository = "https://github.com/Manishearth/triomphe"
description = "A fork of std::sync::Arc with some extra functionality and without weak references (originally servo_arc)"

[lib]
name = "triomphe"
path = "lib.rs"


[dependencies]
nodrop = "0.1.8"
serde = "1.0"
stable_deref_trait = "1.0.0"
