name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build --no-default-features
      run: cargo build --no-default-features --verbose
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test

  miri:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust Nightly
      run: rustup toolchain install nightly --component miri --profile minimal
    - name: Miri Test
      run: cargo +nightly miri test
